name: Manual deploy

on: workflow_dispatch

jobs:
  load:
    runs-on: ubuntu-latest

    steps:
      - name: Load distribution
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success

      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload distribution
        uses: actions/upload-artifact@v2
        with:
          name: distribution
          path: distribution/rando.tar

  deploy:
    needs: load
    uses: ustits/rando/.github/workflows/deploy_workflow.yml@main
    with:
      version: ${{ github.run_id }}
    secrets:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      ssh_port: ${{ secrets.PORT }}
      ssh_key: ${{ secrets.KEY }}